// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CartBlouseTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cartBlouse() {
    // Test name: cartBlouse
    // Step # | name | target | value | comment
    // 1 | open | /index.php |  | 
    driver.get("http://automationpractice.com/index.php");
    // 2 | click | id=search_query_top |  | 
    driver.findElement(By.id("search_query_top")).click();
    // 3 | type | id=search_query_top | blouse | 
    driver.findElement(By.id("search_query_top")).sendKeys("blouse");
    // 4 | click | name=submit_search |  | 
    driver.findElement(By.name("submit_search")).click();
    // 5 | click | css=.ajax_add_to_cart_button > span |  | 
    driver.findElement(By.cssSelector(".ajax_add_to_cart_button > span")).click();
    // 6 | waitForElementVisible | css=.layer_cart_cart | 30000 | 
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".layer_cart_cart")));
    }
    // 7 | assertText | css=.ajax_block_products_total | $27.00 | 
    assertThat(driver.findElement(By.cssSelector(".ajax_block_products_total")).getText(), is("$27.00"));
    // 8 | assertText | css=.ajax_cart_shipping_cost:nth-child(2) | $2.00 | 
    assertThat(driver.findElement(By.cssSelector(".ajax_cart_shipping_cost:nth-child(2)")).getText(), is("$2.00"));
    // 9 | assertText | css=.ajax_block_cart_total:nth-child(2) | $29.00 | 
    assertThat(driver.findElement(By.cssSelector(".ajax_block_cart_total:nth-child(2)")).getText(), is("$29.00"));
  }
}
