// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CartClearTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cartClear() {
    // Test name: cartClear
    // Step # | name | target | value | comment
    // 1 | open | /index.php |  | 
    driver.get("http://automationpractice.com/index.php");
    // 2 | click | css=#homefeatured > .ajax_block_product:nth-child(1) .button:nth-child(1) > span |  | 
    driver.findElement(By.cssSelector("#homefeatured > .ajax_block_product:nth-child(1) .button:nth-child(1) > span")).click();
    // 3 | click | css=.cross |  | 
    driver.findElement(By.cssSelector(".cross")).click();
    // 4 | mouseOver | css=.shopping_cart > a |  | 
    {
      WebElement element = driver.findElement(By.cssSelector(".shopping_cart > a"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 5 | click | css=.ajax_cart_block_remove_link |  | 
    driver.findElement(By.cssSelector(".ajax_cart_block_remove_link")).click();
    // 6 | assertText | css=.ajax_cart_no_product | (empty) | 
    assertThat(driver.findElement(By.cssSelector(".ajax_cart_no_product")).getText(), is("(empty)"));
  }
}
