// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ValidEmailTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void validEmail() {
    // Test name: validEmail
    // Step # | name | target | value | comment
    // 1 | open | /index.php |  | 
    driver.get("http://automationpractice.com/index.php");
    // 2 | click | linkText=Sign in |  | 
    driver.findElement(By.linkText("Sign in")).click();
    // 3 | click | id=email_create |  | 
    driver.findElement(By.id("email_create")).click();
    // 4 | type | id=email_create | patata@brexit.com | 
    driver.findElement(By.id("email_create")).sendKeys("patata@brexit.com");
    // 5 | click | css=#SubmitCreate > span |  | 
    driver.findElement(By.cssSelector("#SubmitCreate > span")).click();
    // 6 | waitForElementPresent | id=account-creation_form | 30000 | 
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.id("account-creation_form")));
    }
    // 7 | assertElementPresent | id=account-creation_form |  | 
    {
      List<WebElement> elements = driver.findElements(By.id("account-creation_form"));
      assert(elements.size() > 0);
    }
  }
}
